#!/bin/sh

# Updated regex to include GitHub issue numbers and made it case-insensitive
ISSUE_REGEX='((#[0-9]+)|((app|dops|web)-?[0-9]+))'
ERROR_MSG="Error: Commit message must contain a ticket token like APP-1, DOPS-2 or a GitHub issue number like #3."


if ! grep -qiE "$ISSUE_REGEX" "$1"; then
  echo "$ERROR_MSG" >&2
fi
